version: '3.7'

services:
  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/target/
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILE_ACTIVE: ${SPRING_PROFILE_ACTIVE}
      SPRING_PROFILES_HTTP_PORT: ${HTTP_PORT}
      SPRING_PROFILES_JPA_SHOW_SQL: ${JPA_SHOW_SQL}

# Volumes
volumes:
  db-data:
